#!/usr/bin/env sh
CONSUL_TEMPLATE_FLAGS=""  

if [ "$CONSUL_TEMPLATE_PROCESS_FLAGS" != "" ]; then
   CONSUL_TEMPLATE_FLAGS="$CONSUL_TEMPLATE_FLAGS $CONSUL_TEMPLATE_PROCESS_FLAGS "
else 
  echo "CONSUL_TEMPLATE_PROCESS_FLAGS variable is not set"; 
fi

if [ "$CONSUL_ADDR" != "" ]; then
   CONSUL_TEMPLATE_FLAGS="$CONSUL_TEMPLATE_FLAGS -consul-addr $CONSUL_ADDR "
else 
  echo "CONSUL_ADDR variable is not set"; 
fi

if [[ "$CONSUL_TEMPLATE_TEMPLATE_PATH" != "" &&  "$CONSUL_TEMPLATE_OUTPUT_PATH" != "" ]]; then
   CONSUL_TEMPLATE_FLAGS="$CONSUL_TEMPLATE_FLAGS -template $CONSUL_TEMPLATE_TEMPLATE_PATH:$CONSUL_TEMPLATE_OUTPUT_PATH "
else 
  echo "CONSUL_TEMPLATE_TEMPLATE_PATH and CONSUL_TEMPLATE_OUTPUT_PATH is not set"; 
fi

echo "Running flags: $CONSUL_TEMPLATE_FLAGS"

consul-template $CONSUL_TEMPLATE_FLAGS -log-level=$LOGGING_LEVEL